// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PeopleRise.Modules.JobReward.Infrastructure;

#nullable disable

namespace PeopleRise.Modules.JobReward.Migrations
{
    [DbContext(typeof(JobRewardDbContext))]
    partial class JobRewardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HelpTextAr")
                        .HasColumnType("text")
                        .HasColumnName("help_text_ar");

                    b.Property<string>("HelpTextEn")
                        .HasColumnType("text")
                        .HasColumnName("help_text_en");

                    b.Property<string>("LabelAr")
                        .HasColumnType("text")
                        .HasColumnName("label_ar");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("answer_options");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.BandPositioningPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid?>("JobFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_family_id");

                    b.Property<string>("Posture")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("posture");

                    b.Property<int>("TargetPercentile")
                        .HasColumnType("integer")
                        .HasColumnName("target_percentile");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JobFamilyId");

                    b.ToTable("band_positioning_policies");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_no");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNo")
                        .IsUnique();

                    b.ToTable("employees");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.EmployeeAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PositionId")
                        .IsUnique()
                        .HasFilter("end_date IS NULL");

                    b.ToTable("employee_assignments");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.EmployeeCompensation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("base_salary");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("employee_compensations");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_employee_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EvaluatorEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluator_employee_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("MethodologyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("methodology_version_id");

                    b.Property<Guid?>("RecommendedGradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommended_grade_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatorEmployeeId");

                    b.HasIndex("JobId");

                    b.HasIndex("MethodologyVersionId");

                    b.HasIndex("RecommendedGradeId");

                    b.ToTable("evaluations");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.EvaluationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnswerOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("answer_option_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("RatingSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("rating_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("AnswerOptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("EvaluationId", "QuestionId", "AnswerOptionId")
                        .IsUnique();

                    b.ToTable("evaluation_answers");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.EvaluationFactorScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<Guid>("FactorId")
                        .HasColumnType("uuid")
                        .HasColumnName("factor_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("FactorId");

                    b.ToTable("evaluation_factor_scores");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Factor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HelpTextAr")
                        .HasColumnType("text")
                        .HasColumnName("help_text_ar");

                    b.Property<string>("HelpTextEn")
                        .HasColumnType("text")
                        .HasColumnName("help_text_en");

                    b.Property<Guid>("MethodologyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("methodology_version_id");

                    b.Property<string>("NameAr")
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("MethodologyVersionId");

                    b.ToTable("factors");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("level_id");

                    b.Property<string>("NameAr")
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LevelId");

                    b.HasIndex("Rank")
                        .IsUnique();

                    b.ToTable("grades");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.GradeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_id");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<Guid>("MethodologyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("methodology_version_id");

                    b.Property<int?>("MinScore")
                        .HasColumnType("integer")
                        .HasColumnName("min_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("MethodologyVersionId", "GradeId")
                        .IsUnique();

                    b.ToTable("grade_mappings", t =>
                        {
                            t.HasCheckConstraint("ck_grade_mapping_score", "max_score >= min_score");
                        });
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_id");

                    b.Property<string>("GradeSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("grade_source");

                    b.Property<Guid?>("JobFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_family_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TitleAr")
                        .HasColumnType("text")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GradeId");

                    b.HasIndex("JobFamilyId");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.JobFamily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NameAr")
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("job_families");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.JobPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_unit_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("JobId");

                    b.HasIndex("OrgUnitId");

                    b.ToTable("job_positions");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NameAr")
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Rank")
                        .IsUnique();

                    b.ToTable("levels");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.MarketDataPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanySize")
                        .HasColumnType("text")
                        .HasColumnName("company_size");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Geography")
                        .HasColumnType("text")
                        .HasColumnName("geography");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_id");

                    b.Property<string>("Industry")
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<Guid?>("JobFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_family_id");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("level_id");

                    b.Property<decimal?>("P25")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("p25");

                    b.Property<decimal?>("P50")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("p50");

                    b.Property<decimal?>("P75")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("p75");

                    b.Property<decimal?>("P90")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("p90");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("market_data_points");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.MarketDataSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("market_data_snapshots");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Methodology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NameAr")
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("methodologies");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.MethodologyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer")
                        .HasColumnName("max_points");

                    b.Property<Guid>("MethodologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("methodology_id");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer")
                        .HasColumnName("min_points");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("MethodologyId", "VersionNo")
                        .IsUnique();

                    b.ToTable("methodology_versions");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.OrgUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("org_units");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FactorId")
                        .HasColumnType("uuid")
                        .HasColumnName("factor_id");

                    b.Property<string>("HelpTextAr")
                        .HasColumnType("text")
                        .HasColumnName("help_text_ar");

                    b.Property<string>("HelpTextEn")
                        .HasColumnType("text")
                        .HasColumnName("help_text_en");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("QuestionTextAr")
                        .HasColumnType("text")
                        .HasColumnName("question_text_ar");

                    b.Property<string>("QuestionTextEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text_en");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("question_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("FactorId");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.SalaryBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_id");

                    b.Property<Guid?>("JobFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_family_id");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_amount");

                    b.Property<decimal>("Midpoint")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("midpoint");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_amount");

                    b.Property<decimal?>("OverlapPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("overlap_pct");

                    b.Property<Guid?>("PositioningId")
                        .HasColumnType("uuid")
                        .HasColumnName("positioning_id");

                    b.Property<Guid?>("SourceSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_snapshot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("JobFamilyId");

                    b.ToTable("salary_bands", t =>
                        {
                            t.HasCheckConstraint("ck_band_order", "max_amount >= midpoint AND midpoint >= min_amount");
                        });
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.SalaryImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Filename")
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("salary_import_batches");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.AnswerOption", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.BandPositioningPolicy", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.JobFamily", "JobFamily")
                        .WithMany()
                        .HasForeignKey("JobFamilyId");

                    b.Navigation("JobFamily");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.EmployeeAssignment", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.JobPosition", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.EmployeeCompensation", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.SalaryImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId");

                    b.Navigation("Employee");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Evaluation", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Employee", "EvaluatorEmployee")
                        .WithMany()
                        .HasForeignKey("EvaluatorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.MethodologyVersion", "MethodologyVersion")
                        .WithMany()
                        .HasForeignKey("MethodologyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Grade", "RecommendedGrade")
                        .WithMany()
                        .HasForeignKey("RecommendedGradeId");

                    b.Navigation("EvaluatorEmployee");

                    b.Navigation("Job");

                    b.Navigation("MethodologyVersion");

                    b.Navigation("RecommendedGrade");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.EvaluationAnswer", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.AnswerOption", "AnswerOption")
                        .WithMany()
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("Evaluation");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.EvaluationFactorScore", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Factor", "Factor")
                        .WithMany()
                        .HasForeignKey("FactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Factor");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Factor", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.MethodologyVersion", "MethodologyVersion")
                        .WithMany("Factors")
                        .HasForeignKey("MethodologyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MethodologyVersion");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Grade", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.GradeMapping", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.MethodologyVersion", "MethodologyVersion")
                        .WithMany("GradeMappings")
                        .HasForeignKey("MethodologyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("MethodologyVersion");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Job", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId");

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.JobFamily", "JobFamily")
                        .WithMany()
                        .HasForeignKey("JobFamilyId");

                    b.Navigation("Grade");

                    b.Navigation("JobFamily");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.JobPosition", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.OrgUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.MarketDataPoint", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.MarketDataSnapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.MethodologyVersion", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Methodology", "Methodology")
                        .WithMany("Versions")
                        .HasForeignKey("MethodologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Methodology");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.OrgUnit", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.OrgUnit", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Question", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Factor", "Factor")
                        .WithMany("Questions")
                        .HasForeignKey("FactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factor");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.SalaryBand", b =>
                {
                    b.HasOne("PeopleRise.Modules.JobReward.Domain.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleRise.Modules.JobReward.Domain.JobFamily", "JobFamily")
                        .WithMany()
                        .HasForeignKey("JobFamilyId");

                    b.Navigation("Grade");

                    b.Navigation("JobFamily");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Factor", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Methodology", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.MethodologyVersion", b =>
                {
                    b.Navigation("Factors");

                    b.Navigation("GradeMappings");
                });

            modelBuilder.Entity("PeopleRise.Modules.JobReward.Domain.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
